npm install -g typescript
tsc
git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"
git checkout master
node out/index.js
if ! git diff-index --quiet HEAD -- then
	echo "changes detected, publishing.."
	echo "1. git add"
	git add .
	echo "2. git commit"
	git commit -m "Autogenerated files [ci skip]"
	echo "3. npm version"
	npm version patch -m "Bumping to %s [ci skip]"
	echo "4. git push"
	git push https://${GIT_TOKEN}@github.com/roblox-ts/rbx-types.git
	echo "5. npm publish"
	npm publish
fi