import path from "path";

export const INCLUDE_FOLDER_PATH = path.join(__dirname, "..", "include");
export const GENERATED_FOLDER_PATH = path.join(INCLUDE_FOLDER_PATH, "generated");
export const TSCONFIG_PATH = path.join(INCLUDE_FOLDER_PATH, "tsconfig.json");
export const CUSTOM_DEFITIONS_PATH = path.join(INCLUDE_FOLDER_PATH, "customDefinitions.d.ts");

/**
 * These classes are tagged as Creatable by the API Dump, probably because they are instantiable to CoreScripts.
 * Developers, however, cannot create these.
 */
export const CREATABLE_BLACKLIST = new Set([
	"UserSettings",
	"DebugSettings",
	"Studio",
	"GameSettings",
	"ParabolaAdornment",
	"LuaSettings",
	"PhysicsSettings",
	"Player",
	"DebuggerWatch",
	"Tween",
	"UserGameSettings",
]);

export const PLUGIN_ONLY_CLASSES = new Set([
	"ABTestService",
	"ChangeHistoryService",
	"CoreGui",
	"DataModelSession",
	"DebuggerBreakpoint",
	"DebuggerManager",
	"DebuggerWatch",
	"DebugSettings",
	"File",
	"GameSettings",
	"GlobalSettings",
	"LuaSettings",
	"MemStorageConnection",
	"MultipleDocumentInterfaceInstance",
	"NetworkPeer",
	"NetworkReplicator",
	"NetworkSettings",
	"PackageService",
	"PhysicsSettings",
	"Plugin",
	"PluginAction",
	"PluginDebugService",
	"PluginDragEvent",
	"PluginGui",
	"PluginGuiService",
	"PluginMenu",
	"PluginMouse",
	"PluginToolbar",
	"PluginToolbarButton",
	"RenderingTest",
	"RenderSettings",
	"RobloxPluginGuiService",
	"ScriptDebugger",
	"ScriptDocument",
	"ScriptEditorService",
	"Selection",
	"StatsItem",
	"Studio",
	"StudioData",
	"StudioService",
	"StudioTheme",
	"TaskScheduler",
	"VersionControlService",
]);

export const CLASS_BLACKLIST = new Set([
	// Classes which Roblox leverages internally/in the CoreScripts but serve no purpose to developers
	"AnalysticsSettings",
	"AppStorageService",
	"BinaryStringValue",
	"BrowserService",
	"CacheableContentProvider",
	"ClusterPacketCache",
	"CookiesService",
	"CorePackages",
	"CoreScript",
	"CoreScriptSyncService",
	"CSGDictionaryService",
	"DraftsService",
	"FlagStandService",
	"FlyweightService",
	"FriendService",
	"Geometry",
	"GoogleAnalyticsConfiguration",
	"GuidRegistryService",
	"HSRDataContentProvider",
	"HttpRbxApiService",
	"HttpRequest",
	"KeyboardService",
	"LocalStorageService",
	"LuaWebService",
	"MemStorageService",
	"MeshContentProvider",
	"MouseService",
	"NonReplicatedCSGDictionaryService",
	"PartOperationAsset",
	"PermissionsService",
	"PhysicsPacketCache",
	"PlayerEmulatorService",
	"RobloxReplicatedStorage",
	"RuntimeScriptService",
	"SolidModelContentProvider",
	"SpawnerService",
	"StandalonePluginScripts",
	"StopWatchReporter",
	"ThirdPartyUserService",
	"TimerService",
	"TouchInputService",
	"UserStorageService",
	"VirtualInputManager",
	"Visit",

	// never implemented
	"AdvancedDragger",
	"LoginService",
	"NotificationService",
	"ScriptService",
	"Status",

	// super deprecated:
	"FunctionalTest",
	"PluginManager",
	"VirtualUser",

	// "BevelMesh",
	"CustomEvent",
	"CustomEventReceiver",
	// "CylinderMesh",
	// "DoubleConstrainedValue",
	"Flag",
	"FlagStand",
	// "FloorWire",
	// "Glue",
	"GuiMain",
	// "Hat",
	"Hint",
	// "Hole",
	"Hopper",
	"HopperBin",
	// "IntConstrainedValue",
	// "JointsService",
	"Message",
	// "MotorFeature",
	"PointsService",
	// "SelectionPartLasso",
	// "SelectionPointLasso",
	// "SkateboardPlatform",
	"Skin",

	"ReflectionMetadata",
	"ReflectionMetadataCallbacks",
	"ReflectionMetadataClass",
	"ReflectionMetadataClasses",
	"ReflectionMetadataEnum",
	"ReflectionMetadataEnumItem",
	"ReflectionMetadataEnums",
	"ReflectionMetadataEvents",
	"ReflectionMetadataFunctions",
	"ReflectionMetadataItem",
	"ReflectionMetadataMember",
	"ReflectionMetadataProperties",
	"ReflectionMetadataYieldFunctions",

	// unused
	"UGCValidationService",
	"RbxAnalyticsService",
]);

export const MEMBER_BLACKLIST = new Map([
	["Workspace", new Set(["FilteringEnabled"])],
	["CollectionService", new Set(["GetCollection"])],
	["Instance", new Set(["children", "Remove"])],
	["BodyGyro", new Set(["cframe"])],
	["BodyAngularVelocity", new Set(["angularvelocity"])],
	["BodyPosition", new Set(["lastForce"])],
	["DataStoreService", new Set(["GetDataFromEmptyScopeDataStoreAsyncTemporary"])],
	["Debris", new Set(["MaxItems"])],
	["LayerCollector", new Set(["GetLayoutNodeTree"])],
	["GuiBase3d", new Set(["Color"])],
	["Model", new Set(["move"])],
	["Players", new Set(["playerFromCharacter", "players"])],
	["ServiceProvider", new Set(["service"])],
	["DataModel", new Set(["lighting"])],
	["PackageLink", new Set(["SerializedDefaultAttributes"])],
]);

export const EXPECTED_EXTRA_MEMBERS = new Map([
	["Player", ["Name"]],
	["ValueBase", ["Value", "Changed"]],
	["DataStore", ["GetAsync", "IncrementAsync", "SetAsync", "UpdateAsync", "RemoveAsync"]],
	["OrderedDataStore", ["GetAsync", "IncrementAsync", "SetAsync", "UpdateAsync", "RemoveAsync"]],
]);
